"""empty message

Revision ID: 16757b7d7628
Revises: 1e926d5be719
Create Date: 2023-05-12 15:35:33.261752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16757b7d7628'
down_revision = '1e926d5be719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    # ### end Alembic commands ###
