"""empty message

Revision ID: 16dc6c5d3808
Revises: e20781f394bd
Create Date: 2023-05-12 16:18:22.896718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dc6c5d3808'
down_revision = 'e20781f394bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
