"""empty message

Revision ID: 1e926d5be719
Revises: dfb79c737901
Create Date: 2023-05-12 14:18:09.561600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e926d5be719'
down_revision = 'dfb79c737901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
