"""empty message

Revision ID: 92087f04d3bb
Revises: 16757b7d7628
Create Date: 2023-05-12 15:42:10.623263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92087f04d3bb'
down_revision = '16757b7d7628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###
